spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.199.92:3306/toilet?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&failOverReadOnly=false&maxReconnects=10&useSSL=false
    username: root
    password: root123
    hikari:
      readOnly: false
      maximum-pool-size: 10
      connection-timeout: 180000
      validationTimeout: 3000
      maxLifetime: 60000
      loginTimeout: 5
      minimum-idle: 10
      connection-test-query: SELECT 1


mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml #指定mapper.xml路径
  global-config:
    db-config:
      id-type: auto #全局默认主键类型设置为自增
  configuration:
    auto-mapping-behavior: partial #只对非嵌套的 resultMap 进行自动映射
    map-underscore-to-camel-case: true #开启自动驼峰命名规则映射
